### ISSUE TITLE
Need Support on Xcode 9 iOS 11 & Swift 4.0

### ISSUE THREAD

**Issue by xcodeApps** [microsoftgraph/ios-swift-snippets-sample#10]
This does not work on latest xcode 9. I need to integrate with Xcode 9 swift 4 are there any other options?

**Comment by JohnMAustin78** [comment]
The sample works only for XCode 7 and Swift 2.  I will add a work item to my backlog to migrate the sample to the current version of XCode and Swift.  Meanwhile, if you have done such a migration, you are welcome to fork this repository, add a branch for your code, and submit a PR to this repo.  I am requesting your help if you are willing to give it because I won't be moving this work item into a sprint until next year. Other people could benefit from your efforts :-)

John

**Comment by jasonjoh** [comment]
This should be resolved with the merge of #13
