### ISSUE TITLE
Stuck in "We're taking you to your organization's sign-in page"

### ISSUE THREAD

**Issue by cartickn** [microsoftgraph/ios-swift-snippets-sample#4]
I'm trying out the sample with a O365 tenant behind an on-premise ADFS so the expectation is that the login view should redirect to the organization's sign-in page, but instead it gets stuck at the screen that says **"We're taking you to your organization's sign-in page".**

The Android sample works just fine with the same O365 tenant so I am sure the problem is not at the on-premise ADFS side.

**Comment by unpluggedk** [comment]
It seems to be an issue with authentication provider, whether it's the adapter or the nxoauth client itself. has this issue been resolved? it's probably the sample adapter referred in this sample.

just to clarify, the repro step is as following, let me know if this is correct or otherwise; 
In the credentials field, type email address, and watch it get stuck.

thanks for letting us know!

**Comment by jamescro** [comment]
Closing for now, since we are tracking what appears to be the same issue here: 
https://github.com/microsoftgraph/ios-objectiveC-snippets-sample/issues/8
